### ISSUE TITLE
Extension fails to load on remotes

### ISSUE THREAD

**Issue by pcjmfranken** [microsoft/vscode-test-adapter-converter#5]
The extension fails to load when connected to remotes. The extension's icon is missing in the extensions panel, and clicking the "repository" link in the extension's info panel crashes the panel.

I've tried reinstalling this extension and its dependants, tried older versions, reloaded the window, cleared the remote cache, but none of this seems to have helped.

Problem started immediately after updating my VSCode to the version listed below. Haven't yet had time to try with an older version, but let me know if you'd like me to!

About VSCode info:
```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0
```

From the dev console:
```
workbench.desktop.main.js:2350 Activating extension 'ms-vscode.test-adapter-converter' failed: Unexpected token '??='.
$onExtensionActivationError @ workbench.desktop.main.js:2350

workbench.desktop.main.js:2350 Cannot activate the 'Test Explorer UI' extension because its dependency 'Test Adapter Converter' failed to activate

$onExtensionActivationError @ workbench.desktop.main.js:2350
workbench.desktop.main.js:2350 Cannot activate the 'Jest Test Explorer' extension because its dependency 'Test Explorer UI' failed to activate
```

From the `Log (Remote Extension Host)` output panel:

```
SyntaxError: Unexpected token '??='
	at wrapSafe (internal/modules/cjs/loader.js:979:16)
	at Module._compile (internal/modules/cjs/loader.js:1027:27)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	at Module.load (internal/modules/cjs/loader.js:928:32)
	at Function.Module._load (internal/modules/cjs/loader.js:769:14)
	at Function.s._load (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:27800)
	at Function.b._load (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:24471)
	at Function.l._load (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:93:59004)
	at Module.require (internal/modules/cjs/loader.js:952:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/loader.js:5:101)
	at c._loadCommonJSModule (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:25877)
	at c._doActivateExtension (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:89:12556)
	at c._activateExtension (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:89:11657)
	at Object.actualActivateExtension (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:89:9202)
	at d._activateExtension (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:97724)
	at /home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:97406
	at Array.map (<anonymous>)
	at d._activateExtensions (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:97394)
	at d._activateExtensions (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:97459)
	at d.activateByEvent (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:94728)
	at c._activateByEvent (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:89:10141)
	at c._handleEagerExtensions (/home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:89:15538)
	at /home/usr/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:89:17891
```

**Comment by amitaiirron** [comment]
Finally! I was trying to understand why Python Test Explorer was failing on remote SSH, and this is the first reference I see to this issue. My stack trace is identical, but has the following line after the last one in the report by @pcjmfranken:

```
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Syntaf** [comment]
Seems this commit introduced a `??=` https://github.com/microsoft/vscode-test-adapter-converter/commit/bde7cd8a38142c670521fe060a34bdbd958f1bf0#diff-e0392fa4619b116ba340f9e72dfe933824ca1ab383850366a3f8e8ff6431104dR17

**Comment by jonculver** [comment]
We are hitting the same problem. I think the issue is that the ??= (nullish assignment) operator is kinda new (here's the PR to add it to Typescript) 

https://github.com/microsoft/TypeScript/pull/37727

But the version on our servers, which I don't have much control over, is probably older. I have verified that changing back to doing the check and assignment longhand fixes the issue.

**Comment by connor4312** [comment]
Thanks for the issue, this was a problem in our version of esbuild not downleveling the conditional assignment operator
